// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Product struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	Description string
	Price       float64
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type ProductCategory struct {
	ProductID  uuid.UUID
	CategoryID uuid.UUID
}

type ProductImage struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	Url       string
	IsPrimary pgtype.Bool
	CreatedAt pgtype.Timestamp
}
