// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_images.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProductImage = `-- name: CreateProductImage :one
INSERT INTO product_images (
    product_id,
    url,
    is_primary
) VALUES (
    $1, $2, $3
) RETURNING id, product_id, url, is_primary, created_at
`

type CreateProductImageParams struct {
	ProductID uuid.UUID
	Url       string
	IsPrimary pgtype.Bool
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, createProductImage, arg.ProductID, arg.Url, arg.IsPrimary)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProductImage = `-- name: DeleteProductImage :exec
DELETE FROM product_images
WHERE id = $1
`

func (q *Queries) DeleteProductImage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductImage, id)
	return err
}

const getProductImages = `-- name: GetProductImages :many
SELECT id, product_id, url, is_primary, created_at FROM product_images
WHERE product_id = $1
ORDER BY is_primary DESC, created_at ASC
`

func (q *Queries) GetProductImages(ctx context.Context, productID uuid.UUID) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, getProductImages, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductImage
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Url,
			&i.IsPrimary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductPrimaryImage = `-- name: GetProductPrimaryImage :one
SELECT id, product_id, url, is_primary, created_at FROM product_images
WHERE product_id = $1 AND is_primary = true
LIMIT 1
`

func (q *Queries) GetProductPrimaryImage(ctx context.Context, productID uuid.UUID) (ProductImage, error) {
	row := q.db.QueryRow(ctx, getProductPrimaryImage, productID)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const setProductPrimaryImage = `-- name: SetProductPrimaryImage :exec
UPDATE product_images
SET is_primary = (id = $2)
WHERE product_id = $1
`

type SetProductPrimaryImageParams struct {
	ProductID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SetProductPrimaryImage(ctx context.Context, arg SetProductPrimaryImageParams) error {
	_, err := q.db.Exec(ctx, setProductPrimaryImage, arg.ProductID, arg.ID)
	return err
}
