// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProductCategory = `-- name: AddProductCategory :exec
INSERT INTO product_categories (product_id, category_id)
VALUES ($1, $2)
`

type AddProductCategoryParams struct {
	ProductID  uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) AddProductCategory(ctx context.Context, arg AddProductCategoryParams) error {
	_, err := q.db.Exec(ctx, addProductCategory, arg.ProductID, arg.CategoryID)
	return err
}

const clearProductCategories = `-- name: ClearProductCategories :exec
DELETE FROM product_categories
WHERE product_id = $1
`

func (q *Queries) ClearProductCategories(ctx context.Context, productID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearProductCategories, productID)
	return err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products(name, slug, description, price, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, name, slug, description, price, created_at, updated_at
`

type CreateProductParams struct {
	Name        string
	Slug        string
	Description string
	Price       float64
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Price,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT 
    p.id,
    p.name,
    p.slug,
    p.description,
    p.price,
    p.created_at,
    p.updated_at,
    pi.url as primary_image_url,
    (
        SELECT json_agg(jsonb_build_object('id', c.id, 'name', c.name, 'slug', c.slug))
        FROM product_categories pc
        JOIN categories c ON c.id = pc.category_id
        WHERE pc.product_id = p.id
    )::json as categories
FROM products p
LEFT JOIN product_images pi ON p.id = pi.product_id AND pi.is_primary = true
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllProductsParams struct {
	Limit  int32
	Offset int32
}

type GetAllProductsRow struct {
	ID              uuid.UUID
	Name            string
	Slug            string
	Description     string
	Price           float64
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	PrimaryImageUrl pgtype.Text
	Categories      []byte
}

func (q *Queries) GetAllProducts(ctx context.Context, arg GetAllProductsParams) ([]GetAllProductsRow, error) {
	rows, err := q.db.Query(ctx, getAllProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProductsRow
	for rows.Next() {
		var i GetAllProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrimaryImageUrl,
			&i.Categories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT 
    p.id,
    p.name,
    p.slug,
    p.description,
    p.price,
    p.created_at,
    p.updated_at,
    pi.url as primary_image_url,
    (
        SELECT json_agg(jsonb_build_object('id', c.id, 'name', c.name, 'slug', c.slug))
        FROM product_categories pc
        JOIN categories c ON c.id = pc.category_id
        WHERE pc.product_id = p.id
    )::json as categories
FROM products p
LEFT JOIN product_images pi ON p.id = pi.product_id AND pi.is_primary = true
WHERE p.id = $1
`

type GetProductByIDRow struct {
	ID              uuid.UUID
	Name            string
	Slug            string
	Description     string
	Price           float64
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	PrimaryImageUrl pgtype.Text
	Categories      []byte
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrimaryImageUrl,
		&i.Categories,
	)
	return i, err
}

const getProductsByCategoryID = `-- name: GetProductsByCategoryID :many
SELECT 
    p.id,
    p.name,
    p.slug,
    p.description,
    p.price,
    p.created_at,
    p.updated_at,
    pi.url as primary_image_url,
    (
        SELECT json_agg(jsonb_build_object('id', c.id, 'name', c.name, 'slug', c.slug))
        FROM product_categories pc_all
        JOIN categories c ON c.id = pc_all.category_id
        WHERE pc_all.product_id = p.id
    )::json as categories
FROM products p
JOIN product_categories pc ON p.id = pc.product_id
LEFT JOIN product_images pi ON p.id = pi.product_id AND pi.is_primary = true
WHERE pc.category_id = $1
`

type GetProductsByCategoryIDRow struct {
	ID              uuid.UUID
	Name            string
	Slug            string
	Description     string
	Price           float64
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	PrimaryImageUrl pgtype.Text
	Categories      []byte
}

func (q *Queries) GetProductsByCategoryID(ctx context.Context, categoryID uuid.UUID) ([]GetProductsByCategoryIDRow, error) {
	rows, err := q.db.Query(ctx, getProductsByCategoryID, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsByCategoryIDRow
	for rows.Next() {
		var i GetProductsByCategoryIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrimaryImageUrl,
			&i.Categories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsCount = `-- name: GetProductsCount :one
SELECT COUNT(*) FROM products
`

func (q *Queries) GetProductsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getProductsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET 
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    price = COALESCE($4, price),
    updated_at = NOW()
WHERE id = $1
`

type UpdateProductParams struct {
	ID          uuid.UUID
	Name        string
	Description string
	Price       float64
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
	)
	return err
}
