// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products(name, slug, description, category_id, price, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, name, slug, description, category_id, price, created_at, updated_at
`

type CreateProductParams struct {
	Name        string
	Slug        string
	Description string
	CategoryID  uuid.UUID
	Price       float64
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.CategoryID,
		arg.Price,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CategoryID,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT 
    p.id,
    p.name,
    p.slug,
    p.description,
    p.category_id,
    p.price,
    p.created_at,
    p.updated_at,
    pi.url as primary_image_url
FROM products p
LEFT JOIN product_images pi ON p.id = pi.product_id AND pi.is_primary = true
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllProductsParams struct {
	Limit  int32
	Offset int32
}

type GetAllProductsRow struct {
	ID              uuid.UUID
	Name            string
	Slug            string
	Description     string
	CategoryID      uuid.UUID
	Price           float64
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	PrimaryImageUrl pgtype.Text
}

func (q *Queries) GetAllProducts(ctx context.Context, arg GetAllProductsParams) ([]GetAllProductsRow, error) {
	rows, err := q.db.Query(ctx, getAllProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProductsRow
	for rows.Next() {
		var i GetAllProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CategoryID,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrimaryImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByCategory = `-- name: GetProductByCategory :many
SELECT 
    p.id,
    p.name,
    p.slug,
    p.description,
    p.category_id,
    p.price,
    p.created_at,
    p.updated_at,
    pi.url as primary_image_url
FROM products p
LEFT JOIN product_images pi ON p.id = pi.product_id AND pi.is_primary = true
WHERE p.category_id = $1
`

type GetProductByCategoryRow struct {
	ID              uuid.UUID
	Name            string
	Slug            string
	Description     string
	CategoryID      uuid.UUID
	Price           float64
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	PrimaryImageUrl pgtype.Text
}

func (q *Queries) GetProductByCategory(ctx context.Context, categoryID uuid.UUID) ([]GetProductByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getProductByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductByCategoryRow
	for rows.Next() {
		var i GetProductByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CategoryID,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrimaryImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT 
    p.id,
    p.name,
    p.slug,
    p.description,
    p.category_id,
    p.price,
    p.created_at,
    p.updated_at,
    pi.url as primary_image_url
FROM products p
LEFT JOIN product_images pi ON p.id = pi.product_id AND pi.is_primary = true
WHERE p.id = $1
`

type GetProductByIDRow struct {
	ID              uuid.UUID
	Name            string
	Slug            string
	Description     string
	CategoryID      uuid.UUID
	Price           float64
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	PrimaryImageUrl pgtype.Text
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CategoryID,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrimaryImageUrl,
	)
	return i, err
}

const getProductsCount = `-- name: GetProductsCount :one
SELECT COUNT(*) FROM products
`

func (q *Queries) GetProductsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getProductsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET 
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    category_id = COALESCE($4, category_id),
    updated_at = NOW()
WHERE id = $1
`

type UpdateProductParams struct {
	ID          uuid.UUID
	Name        string
	Description string
	CategoryID  uuid.UUID
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CategoryID,
	)
	return err
}
